package codex.apps.siteexporter;

import org.jsoup.Jsoup;
import org.jsoup.nodes.Comment;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Node;

import java.util.Objects;

/**
 * Detects whether an HTML document was generated by pdf2htmlEX.
 *
 * <p>Three independent signals are checked; a positive on any one is sufficient:</p>
 * <ol>
 *   <li>{@code <meta name="generator" content="pdf2htmlEX">} in the head.</li>
 *   <li>An HTML comment containing {@code pdf2htmlEX} (the "Created by" line).</li>
 *   <li>A structural fingerprint: {@code #page-container} element, at least one
 *       {@code .pf} page-frame element, and at least one {@code .t} text span.</li>
 * </ol>
 */
public final class Pdf2HtmlExDetector {

    /**
     * Returns {@code true} if {@code doc} appears to have been generated by pdf2htmlEX.
     *
     * @param doc parsed Jsoup document; must not be {@code null}
     * @return {@code true} if any pdf2htmlEX signal is found
     */
    public boolean detect(final Document doc) {
        Objects.requireNonNull(doc, "doc");
        return hasGeneratorMeta(doc) || hasCreatedByComment(doc) || hasStructuralFingerprint(doc);
    }

    /**
     * Parses {@code html} and returns {@code true} if it appears to have been generated
     * by pdf2htmlEX.
     *
     * @param html    raw HTML string; must not be {@code null}
     * @param baseUri base URI for relative reference resolution; must not be {@code null}
     * @return {@code true} if any pdf2htmlEX signal is found
     */
    public boolean detect(final String html, final String baseUri) {
        Objects.requireNonNull(html, "html");
        Objects.requireNonNull(baseUri, "baseUri");
        return detect(Jsoup.parse(html, baseUri));
    }

    // ------------------------------------------------------------------
    // Signal checks
    // ------------------------------------------------------------------

    private static boolean hasGeneratorMeta(final Document doc) {
        return doc.select("meta[name=generator]").stream()
                .anyMatch(m -> m.attr("content").toLowerCase().contains("pdf2htmlex"));
    }

    private static boolean hasCreatedByComment(final Document doc) {
        // Comments may appear as direct children of the document node or of the body.
        if (hasCommentContaining(doc.childNodes(), "pdf2htmlex")) {
            return true;
        }
        if (doc.body() != null && hasCommentContaining(doc.body().childNodes(), "pdf2htmlex")) {
            return true;
        }
        return false;
    }

    private static boolean hasCommentContaining(final Iterable<Node> nodes, final String token) {
        for (final Node node : nodes) {
            if (node instanceof Comment c && c.getData().toLowerCase().contains(token)) {
                return true;
            }
        }
        return false;
    }

    private static boolean hasStructuralFingerprint(final Document doc) {
        return !doc.select("#page-container").isEmpty()
                && !doc.select(".pf").isEmpty()
                && !doc.select(".t").isEmpty();
    }
}
